### ISSUE TITLE
Code does not compile on with GCC 8.1

### ISSUE THREAD

**Issue by MichaelGoodale** [mlml/autovot#78]
Hi,
I recently tried to build autovot on Arch Linux. Unfortunately it crashes when I try to compile it, with the following error.
```
/home/michael/autovot/autovot/code/learning_tools/htk_utils/txt2htk.cpp:41:31: error: cannot convert ‘std::basic_istream<char>’ to ‘bool’ in return
   bool next() { return in_ >> token_; }
```

This seems to be due to GCC defaulting to C++14 now according to [this](https://stackoverflow.com/questions/38659115/make-fails-with-error-cannot-convert-stdistream-aka-stdbasic-istreamchar). I was able to successfully compile the code by adding "-std=c++03" to the CXXFLAGS var of ```learning_tools/htk_utils/Makefile```.

**Comment by jkeshet** [comment]
Thanks! Can you please make the changes to support C++14?

**Comment by msonderegger** [comment]
@MichaelGoodale could you change the file you mention and make a pull request?  Thanks!
